#!/bin/sh -x

if ! git submodule update --init --recursive
then
  exit 1
fi

git submodule foreach --recursive git clean -f -x -d

mkdir lib/libgit2sharp/cmake-build
cd lib/libgit2sharp/cmake-build
if ! cmake -DTHREADSAFE=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_CLAR=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX=./libgit2-bin ../libgit2
then
  exit 2
fi
if ! cmake --build . --target install
then
  exit 3
fi

export LD_LIBRARY_PATH=$PWD/libgit2-bin/lib

cd ../../..
if ! xbuild CI.proj
then
  exit 5
fi
