//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("GitTfs")]
[assembly: AssemblyProduct("GitTfs")]
[assembly: AssemblyVersion("0.31.23")]
[assembly: AssemblyFileVersion("0.31.23")]
[assembly: AssemblyInformationalVersion("0.31.23+eb7abf0078a6bfef2bd5763d83aaf0c842cdbf21.local")]
[assembly: AssemblyCopyright("Copyright © 2009-2020")]

